const express = require('express');
const controller = require('../controllers/financeController');
const { protect } = require('../middleware/authMiddleware');
const { authorizeRoles } = require('../middleware/roleMiddleware');
const router = express.Router();
const financeRead = [protect, authorizeRoles('Admin', 'Store_Manager', 'Accounts/Finance', 'Auditor')];
const financeWrite = [protect, authorizeRoles('Admin', 'Store_Manager', 'Accounts/Finance')];
router.get('/expenses', ...financeRead, controller.listExpenses);
router.post('/expenses', ...financeWrite, controller.createExpense);
router.put('/expenses/:id', ...financeWrite, controller.updateExpense);
router.delete('/expenses/:id', ...financeWrite, controller.deleteExpense);
router.get('/income', ...financeRead, controller.listIncome);
router.post('/income', ...financeWrite, controller.createIncome);
router.put('/income/:id', ...financeWrite, controller.updateIncome);
router.delete('/income/:id', ...financeWrite, controller.deleteIncome);
module.exports = router;
