import React, { useEffect, useState } from 'react';
import { TrendingUp } from 'lucide-react';
import { createIncome, deleteIncome, getIncome, updateIncome } from '../services/financeService';

const blank = { title: '', source: '', amount: '', date: new Date().toISOString().slice(0, 10) };
const Income = () => {
  const [income, setIncome] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  const load = async () => { try { const response = await getIncome(); setIncome(response.data.data || []); } catch (err) { setError(err.response?.data?.message || 'Unable to load income'); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); try { if (editing) await updateIncome(editing, form); else await createIncome(form); setForm(blank); setEditing(null); load(); } catch (err) { setError(err.response?.data?.message || 'Unable to save income'); } };
  const edit = (item) => { if (item.referenceType !== 'manual') return; setEditing(item._id); setForm({ title: item.title, source: item.source, amount: item.amount, date: item.date.slice(0, 10) }); };
  const remove = async (item) => { if (item.referenceType === 'manual' && window.confirm('Delete this income entry?')) { await deleteIncome(item._id); load(); } };
  return <div className="min-h-screen bg-[#064e3b] text-white p-6 lg:p-8 -m-4 lg:-m-8"><header className="flex items-center gap-3 mb-8"><TrendingUp className="text-[#10b981]" size={30} /><div><h1 className="text-3xl font-bold">Income</h1><p className="text-gray-300 text-sm">Manual income and completed Sale income.</p></div></header>{error && <p className="mb-4 text-red-200">{error}</p>}<form onSubmit={submit} className="bg-white/10 border border-white/15 rounded-2xl p-5 mb-6 grid grid-cols-1 md:grid-cols-4 gap-3 items-end"><label className="text-sm text-gray-300">Title<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="mt-1 w-full input" /></label><label className="text-sm text-gray-300">Source<input required value={form.source} onChange={e => setForm({ ...form, source: e.target.value })} className="mt-1 w-full input" /></label><label className="text-sm text-gray-300">Amount<input required min="0" type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} className="mt-1 w-full input" /></label><button className="rounded-lg bg-[#10b981] px-4 py-2.5 font-semibold">{editing ? 'Update' : 'Add Manual Income'}</button></form><table className="min-w-full bg-white/10 rounded-2xl overflow-hidden"><thead className="bg-white/5 text-left text-gray-300"><tr><th className="p-4">Title</th><th className="p-4">Source</th><th className="p-4">Amount</th><th className="p-4">Type</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y divide-white/10">{income.map(item => <tr key={item._id}><td className="p-4">{item.title}</td><td className="p-4">{item.source}</td><td className="p-4">Rs. {item.amount.toLocaleString()}</td><td className="p-4">{item.referenceType === 'sale' ? 'Sale-linked' : 'Manual'}</td><td className="p-4">{item.referenceType === 'manual' ? <><button onClick={() => edit(item)} className="text-blue-300 mr-4">Edit</button><button onClick={() => remove(item)} className="text-red-300">Delete</button></> : <span className="text-gray-500">Read-only</span>}</td></tr>)}</tbody></table></div>;
};
export default Income;
